spring:
  application:
    name: testRabbitMQ
  profiles:
    active: dev
  rabbitmq:
    host: jiangxj-01.com
    port: 5672
    username: admin
    password: 123456
    publisher-confirms: true

server:
  port: 1001