server:
  port: 8081
  compression:
    enabled: true
spring:
  application:
    name: test1-cache
  datasource:
    url: jdbc:mysql://jiangxj-02.com:3306/mytest
    username: root
    password: mysql
    tomcat:
      driver-class-name: com.mysql.jdbc.Driver
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 10800
      max-active: 8
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)
  cache:
    type: redis
  redis:
    pool.max-idle: 10
    pool.max-active: 10
    pool.min-idle: 5
    pool.max-wait: 2000
    timeout: 5000
    host: jiangxj-02.com
    password: test123
    port: 6379
    database: 2